##
## config.yml - The configuration file for KnuttBinAnno
##


#
# Input/Output files
#

# Where to look for the bins
bin_input_dir: "input"

# The naming pattern for the bins
# Use the wildcard {bin}
bin_files: "{bin}.fa"

# Where to place the output files
output_dir: "output"

# Where to place reference/database files
reference_dir: "reference_data"

# Number of chunks to use for annotation
chunk_count: 8

min_contiglen: 200
min_orflen: 180

sourmash_kmers: "21,31,51"
sourmash_scaled: 10000
sourmash_compare_kmer: "31"

dbCAN_diamond_eval: 1.0e-102
hotpep_hits: 6
hotpep_freq: 2.6
cazy_hmmscan_eval: 1.0e-15
cazy_hmmscan_cov: 0.35
tf_hmmscan_eval: 1.0e-4
tf_hmmscan_cov: 0.35
stp_hmmscan_eval: 1.0e-4
stp_hmmscan_cov: 0.3
tcdb_diamond_eval: 1.0e-10
dbcan_cgc_maxnotdbcangenespacers: 1

eggnog_eval: 0.001
eggnog_minscore: 60


kofam_helper_eval: 1.0e-10
